site_name: exoInference
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/exoInference
  
