site_name: exoInference
theme:
  name: material
nav:
    - Home: index.md
    - About: about.md
    - Publications: publications.md
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
